### ISSUE TITLE
General layout issue

### ISSUE THREAD

**Issue by RaminMammadzada** [tadeuasarro/DesignTeardown#2]
There are white areas on the left and right side of the page, as you see it below:
![image](https://user-images.githubusercontent.com/4702114/85738138-7643d600-b708-11ea-9e17-65adbfd407f0.png)

**Comment by tadeuasarro** [comment]
Yeah mate, I reckon that's because of responsiveness, gonna do that after putting all elements on display.

**Comment by Prabhakarzx** [comment]
### Thank You @RaminMammadzada !
**Your reviews and suggestions helped us a lot!**
We've fixed all the required changes and we're submitting the project.
_Have a great Day!_
**Thank You!**
