### ISSUE TITLE
The general requirement about the project

### ISSUE THREAD

**Issue by RaminMammadzada** [tadeuasarro/DesignTeardown#3]
You must make a heatmap of the page, not the copy.
The example heatmap of that page is below:

![image](https://user-images.githubusercontent.com/4702114/85738843-0255fd80-b709-11ea-8012-1f68185e85dc.png)

**Comment by tadeuasarro** [comment]
I understand that, but also these sort of stuff will depend on the TSE that's evaluating the project, a dude in my team got his project approved with the original colors, so that's something to bear in mind.

**Comment by Prabhakarzx** [comment]
### Thank You @RaminMammadzada 
**Your reviews and suggestions helped us a lot!**
We've fixed all the required changes and want to thanks once again for your early insight!
**Thank You!**
