### ISSUE TITLE
The images in the page should be changed.

### ISSUE THREAD

**Issue by RaminMammadzada** [tadeuasarro/DesignTeardown#5]
All of the images on the page should be changed with the image placeholders, like in the examples below:

![image](https://user-images.githubusercontent.com/4702114/85739654-a6d83f80-b709-11ea-9904-d9fe178a0481.png)

![image](https://user-images.githubusercontent.com/4702114/85739689-ae97e400-b709-11ea-8862-2efd8cbb532e.png)

**Comment by Prabhakarzx** [comment]
### Thank you for the valuable time taken to review the code @RaminMammadzada 
Changes have been implemented!
**Thanks!**
